apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: KeystoreRsaGenerated
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/keystorersagenerated
  labels:
    testing.upbound.io/example-name: keystore_rsa_generated
  name: keystore-rsa-generated
spec:
  forProvider:
    active: true
    algorithm: RS256
    enabled: true
    keySize: 2048
    name: my-rsa-generated-key
    priority: 100
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/keystorersagenerated
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    realm: my-realm
